"""Shared user-facing labels for questionnaire topics."""

FILTERABLE_TAGS: tuple[tuple[str, str], ...] = (
    ("group:vosh", "Вся группа ВсОШ"),
    ("group:mosh", "Вся группа МОШ"),
    ("cybersecurity", "Информационная безопасность"),
    ("informatics", "Информатика"),
    ("programming", "Программирование"),
    ("algorithms", "Алгоритмы"),
    ("ai", "Искусственный интеллект"),
    ("mathematics", "Математика"),
    ("engineering", "Инженерия"),
    ("robotics", "Робототехника"),
    ("technology", "Технология"),
    ("physics", "Физика"),
    ("ecology", "Экология"),
    ("law", "Право"),
    ("obzr", "ОБЗР"),
    ("social-science", "Обществознание"),
    ("economics", "Экономика"),
    ("financial-literacy", "Финграмотность"),
    ("biology", "Биология"),
    ("chemistry", "Химия"),
    ("geography", "География"),
    ("astronomy", "Астрономия"),
    ("history", "История"),
    ("literature", "Литература"),
    ("linguistics", "Лингвистика"),
    ("english", "Английский язык"),
    ("art", "Искусство"),
    ("research", "Исследования"),
    ("preprofessional", "Предпрофиль"),
    ("team", "Командные"),
)
TAG_LABELS: dict[str, str] = dict(FILTERABLE_TAGS)
